DELETE http://localhost:3003/api/blogs/65cb2bc2cf3d8ed4a3331eb8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlZXR0YSIsImlkIjoiNjVjYjI0ZGZkZjY0ZjIwMjk3YzU1MDIxIiwiaWF0IjoxNzA3ODIyMzczLCJleHAiOjE3MDc4MjU5NzN9.KWgs1HHwn-ScuWF1kOa_1LIgj5kN1CuvtCIh8osidJg